name: Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: Ilshat/discord-webhook-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "🚀 **Novo push realizado com sucesso no repositório!**"