name: Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 Novo evento/commit registrado no repositório!"